AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys Lambda functions, a Lambda layer, and a DynamoDB table, along with IAM roles for necessary permissions.

Parameters:
  Region:
    Type: String
    Description: Specifies the AWS region for resource creation.
    Default: us-east-1

  AccountId:
    Type: String
    Description: AWS account ID for resource deployment.
    Default: !Ref "AWS::AccountId"

  EnvironmentName:
    Type: String
    Description: Name of the environment (e.g., development, staging, production).
    Default: dev

  UserTokensTableName:
    Type: String
    Description: Name of the DynamoDB table for storing user tokens.
    Default: UserTokensTable
  
  SenderEmail:
    Type: String
    Description: Email address from which verification tokens will be sent.
    Default: mumtaz.workmail@gmail.com
  
  SecretKeyJwtToken:
    Type: String
    Description: Key used for signing JWT tokens.
    Default: secret_key
  
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for Lambda zip files and the JWT Python layer.
    Default: devopsassignmentccl

Resources:
  # DynamoDB Table for User Tokens
  UserTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UserTokensTableName
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED

  # IAM Role for Token Creation Lambda Function
  TokenCreationLambdaRole:  
    Type: AWS::IAM::Role  
    Properties:  
      RoleName: TokenCreationLambdaRole  
      AssumeRolePolicyDocument:  
        Version: "2012-10-17"  
        Statement:  
          - Effect: Allow  
            Principal:  
              Service: lambda.amazonaws.com  
            Action: sts:AssumeRole  
      Policies:  
        - PolicyName: TokenCreationLambdaPolicy  
          PolicyDocument:  
            Version: "2012-10-17"  
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'    
              - Effect: Allow  
                Action:  
                  - dynamodb:PutItem  
                  - dynamodb:GetItem  
                  - dynamodb:UpdateItem  
                Resource: !GetAtt UserTokensTable.Arn
              - Effect: Allow  
                Action:  
                  - lambda:InvokeFunction  
                Resource: !GetAtt SendCodeLambda.Arn

  # IAM Role for Sending Verification Code Lambda Function
  SendCodeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SendCodeLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SendCodeLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"
    
  # IAM Role for Token Verification Lambda Function
  TokenVerificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TokenVerificationLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TokenVerificationLambdaPolicy  
          PolicyDocument:  
            Version: "2012-10-17"  
            Statement:  
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'  
              - Effect: Allow  
                Action:  
                  - dynamodb:PutItem  
                  - dynamodb:GetItem  
                  - dynamodb:UpdateItem  
                  - dynamodb:Scan  
                Resource: !GetAtt UserTokensTable.Arn


  # Lambda Layer Definition
  JWTLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: JWTLayer
      Description: "A Lambda Layer containing the JWT Python library."
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: jwtpythonlayer.zip
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: "MIT"

  # Lambda Function for Token Creation
  TokenCreationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TokenCreationLambda
      Handler: lambda_function.lambda_handler
      Role: !GetAtt TokenCreationLambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: token_creation_lambda.zip
      Runtime: python3.8
      Layers:
        - !Ref JWTLayer
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          SendVerificationCodeLambdaArn: !GetAtt SendCodeLambda.Arn
          Region: !Ref Region
          AccountId: !Ref AccountId
          EnvironmentName: !Ref EnvironmentName
          UserTokensTableName: !Ref UserTokensTableName
          SenderEmail: !Ref SenderEmail
          SecretKeyJwtToken: !Ref SecretKeyJwtToken
    
  # Lambda Function for Token Verification
  TokenVerificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TokenVerificationLambda
      Handler: lambda_function.lambda_handler
      Role: !GetAtt TokenVerificationLambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: token_verification_lambda.zip
      Runtime: python3.8
      Layers:
        - !Ref JWTLayer
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          UserTokensTableName: !Ref UserTokensTableName
          SecretKeyJwtToken: !Ref SecretKeyJwtToken

  # Lambda Function for Sending Verification Code
  SendCodeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SendCodeLambda
      Handler: lambda_function.lambda_handler
      Role: !GetAtt SendCodeLambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: send_code_lambda.zip
      Runtime: python3.8
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          Region: !Ref Region

  # API Gateway Setup for Token Creation
  TokenCreationAPI:  
    Type: AWS::ApiGateway::RestApi  
    Properties:  
      Name: TokenCreationAPI  
      Description: API endpoint for creating tokens.  
      EndpointConfiguration:  
        Types:  
          - EDGE  

  TokenCreationResource:  
    Type: AWS::ApiGateway::Resource  
    Properties:  
      RestApiId: !Ref TokenCreationAPI  
      ParentId: !GetAtt TokenCreationAPI.RootResourceId  
      PathPart: "createToken"  
    DependsOn: TokenCreationAPI # Ensure the API is provisioned before adding resources.

  # Adding Token Verification Resource to the API Gateway  
  TokenVerificationResource:  
    Type: AWS::ApiGateway::Resource  
    Properties:  
      RestApiId: !Ref TokenCreationAPI  
      ParentId: !GetAtt TokenCreationAPI.RootResourceId   
      PathPart: "tokenVerification"   
    DependsOn: TokenCreationAPI  

  CreateTokenMethod:  
    Type: AWS::ApiGateway::Method  
    Properties:  
      RestApiId: !Ref TokenCreationAPI  
      ResourceId: !Ref TokenCreationResource  
      HttpMethod: POST  
      AuthorizationType: NONE  
      Integration:  
        IntegrationHttpMethod: POST  
        Type: AWS_PROXY  
        Uri: !Sub  
          - arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations  
          - Region: !Ref "AWS::Region"  
            LambdaArn: !GetAtt TokenCreationLambda.Arn  
      MethodResponses:  
        - StatusCode: 200  
          ResponseModels:  
            "application/json": "Empty"  
        - StatusCode: 400  
          ResponseModels:  
            "application/json": "Empty"  
        - StatusCode: 500  
          ResponseModels:  
            "application/json": "Empty"  
    DependsOn: TokenCreationResource # Ensure the resource is ready before defining methods.
  
  TokenVerificationMethod:  
    Type: AWS::ApiGateway::Method  
    Properties:  
      RestApiId: !Ref TokenCreationAPI  
      ResourceId: !Ref TokenVerificationResource  
      HttpMethod: POST  
      AuthorizationType: NONE  
      Integration:  
        IntegrationHttpMethod: POST  
        Type: AWS_PROXY  
        Uri: !Sub  
          - arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations  
          - Region: !Ref "AWS::Region"  
            LambdaArn: !GetAtt TokenVerificationLambda.Arn  
      MethodResponses:  
        - StatusCode: 200  
          ResponseModels:  
            "application/json": "Empty"  
        - StatusCode: 400  
          ResponseModels:  
            "application/json": "Empty"  
        - StatusCode: 500  
          ResponseModels:  
            "application/json": "Empty"  
    DependsOn: TokenVerificationResource 

  # Permissions for API Gateway to Invoke Lambda Functions  
  TokenCreationLambdaPermission:  
    Type: AWS::Lambda::Permission  
    Properties:  
      FunctionName: !GetAtt TokenCreationLambda.Arn  
      Action: lambda:InvokeFunction  
      Principal: apigateway.amazonaws.com  
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TokenCreationAPI}/*/POST/createToken"

  TokenVerificationLambdaPermission:  
    Type: AWS::Lambda::Permission  
    Properties:  
      FunctionName: !GetAtt TokenVerificationLambda.Arn  
      Action: lambda:InvokeFunction  
      Principal: apigateway.amazonaws.com  
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TokenCreationAPI}/*/POST/tokenVerification" 

  # Deployment Configuration for API Gateway  
  TokenCreationDeployment:  
    Type: AWS::ApiGateway::Deployment  
    Properties:  
      RestApiId: !Ref TokenCreationAPI  
    DependsOn: CreateTokenMethod # Ensure the method is set up before deployment.  

  # Stage Configuration for API Gateway  
  TokenCreationStage:  
    Type: AWS::ApiGateway::Stage  
    Properties:  
      StageName: !Ref EnvironmentName  
      RestApiId: !Ref TokenCreationAPI  
      DeploymentId: !Ref TokenCreationDeployment  
    DependsOn: TokenCreationDeployment # Ensure deployment is complete before creating the stage.

  # Log Groups for Monitoring Lambda Functions  
  TokenCreationLambdaLogGroup:  
    Type: AWS::Logs::LogGroup  
    Properties:  
      LogGroupName: "/aws/lambda/TokenCreationLambda"  

  TokenVerificationLambdaLogGroup:  
    Type: AWS::Logs::LogGroup  
    Properties:  
      LogGroupName: "/aws/lambda/TokenVerificationLambda"

  SendCodeLambdaLogGroup:  
    Type: AWS::Logs::LogGroup  
    Properties:  
      LogGroupName: "/aws/lambda/SendCodeLambda"  

Outputs:  
  UserTokensTableArn:  
    Description: "The ARN of the UserTokensTable DynamoDB Table."  
    Value: !GetAtt UserTokensTable.Arn  

  TokenCreationLambdaArn:  
    Description: "The ARN of the Token Creation Lambda Function."  
    Value: !GetAtt TokenCreationLambda.Arn  

  JWTLayerArn:  
    Description: "The ARN of the JWT Lambda Layer."  
    Value: !Ref JWTLayer  

  TokenCreationLambdaRoleArn:  
    Description: "The ARN of the IAM Role for Token Creation Lambda Execution."  
    Value: !GetAtt TokenCreationLambdaRole.Arn  

  SendCodeLambdaArn:  
    Description: "The ARN of the Send Verification Code Lambda Function."  
    Value: !GetAtt SendCodeLambda.Arn  

  SendCodeLambdaRoleArn:  
    Description: "The ARN of the IAM Role for Send Verification Code Lambda Execution."  
    Value: !GetAtt SendCodeLambdaRole.Arn

  TokenCreationAPIURL:
    Description: "The URL of the Token Creation API Gateway."
    Value: !Sub "https://${TokenCreationAPI}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/createToken"

  TokenVerificationAPIURL:
    Description: "The URL of the Token Verification API Gateway."
    Value: !Sub "https://${TokenCreationAPI}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/tokenVerification"
